name: GitHub pages

on:
  push:
    branches:
      - jsdoc-testing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
            node-version: 16
            
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./admin/testingCI/
          
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    deploy_key: ${{secrets.S6KrXtaPgLC1L4KB7tkPcEcEDzWRWO2hVKNIcmmaygM}}
      #    publish_dir: ./out
