name: JSDoc

on:
  push:
    branches:
      - jsdoc-testing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
     # - name: docsify-action
        # You may pin to the exact commit or the version.
      # uses: tool3/docsify-action@0221337ae139ac03ef834b9705a13395d587ba0e
       # uses: tool3/docsify-action@v1.0.3
       # with:
    # github access token
       #   github_token: 
    # destination dir
       #   dir: ./docs
    # destination branch
       #   branch: # optional, default is master
    # docsify-cli args
       #   docsify_args: # optional

          
          
      #- name: Install Dependencies
      #  run: |
      #    npm i docsify-cli -g
      #    docsify init ./docs
          
      - name: JSDoc Action
      # You may pin to the exact commit or the version.
      # uses: andstor/jsdoc-action@06eafccd94e3fedcbf4ff0a8f23d775c169efdf2
        uses: andstor/jsdoc-action@v1.2.1
        with:
        # Source directory to build documentation from
          source_dir: ./admin/testingCI
        # Output folder for the generated documentation
          output_dir: ./out
        #node version  
          node-version: '16'
      #- name: Build
      #  uses: andstor/jsdoc-action@v1.2.1
      #  with:
      #    source_dir: ./admin/testingCI/
        
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    deploy_key: ${{secrets.S6KrXtaPgLC1L4KB7tkPcEcEDzWRWO2hVKNIcmmaygM}}
      #    publish_dir: ./out
