name: GitHub pages

on:
  push:
    branches:
      - jsdoc-testing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./admin/testingCI/
          using: 'Node 16'
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${S6KrXtaPgLC1L4KB7tkPcEcEDzWRWO2hVKNIcmmaygM}
          publish_dir: ./out
