name: JSDOC

on: [pull_request, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./admin/testingCI/
          output_dir: ./admin/testingCI/documentations/
          recurse: true
          config_file: jsdoc.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./admin/testingCI/documentations/

      # - name: Installation
      #   run: npm install
      # - name: JSDOC
      #   run: npm run doc