- name: JSDoc Action
  uses: andstor/jsdoc-action@v1.2.1
    with:
    # Source directory to build documentation from
    source_dir: ./admin/testingCI/
    # Output folder for the generated documentation
    output_dir: ./admin/testingCI/documentation
    # Recurse into subdirectories when scanning for source files
    recurse: true
