name: GitHub pages

on:
  push:
    branches:
      - jsdoc-testing
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16' 
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16' 
          
      - name: Install Dependencies
        run: |
          npm install -g jsdoc
          jsdoc ./admin/testingCI/
        
      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./admin/testingCI/
          node-version: '16' 
        
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    deploy_key: ${{secrets.S6KrXtaPgLC1L4KB7tkPcEcEDzWRWO2hVKNIcmmaygM}}
      #    publish_dir: ./out
