name: JSDOC

on: [pull_request, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/
          output_dir: ./documentations/
          config_file: jsdoc.json
          template: minami
          recurse: true