name: JSDoc

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
        
      - name: run properties
        run: |
          npm i -g jsdoc
          npm fund
          jsdoc ./source/*
          
      - name: Add & Commit
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
