name: JSDoc

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
          
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
        # Source directory to build documentation from
            source_dir: ./source/
            recurse: true
            output_dir: docs
      #- name: run properties
      #  run: |
      #    npm i -g jsdoc
      #    npm fund
      #    jsdoc -r ./source/*
          
      - name: Add & Commit
        uses: stefanzweifel/git-auto-commit-action@v4
